L=../../scripts/pdf

INS=\
  01-intro.md \
  02-oldcontext.md \
  03-newcontext.md \
  04-sosodocs.md \
  05-newdocs.md \
  06-example.md \
  07-whyitmatter.md \
  08-conclusion.md \
  A0-appendix.md

NAME=frame

include $L/Makefile

